name: Java CI with Maven in Linux

on:
  push:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
       matrix:
          java: [ 8, 11 ]
          include: 
             - java: 8
               maven-args: "-DrepoToken=$COVERALLS_REPO_TOKEN coveralls:report"
             - java: 11
               maven-args: "sonar:sonar -Dsonar.projectKey=Manuel985_apt-progetto"
    
    steps:
    - uses: actions/checkout@v3
      with:
         fetch-depth: 0
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
         java-version: ${{ matrix.java }}
    - name: Cache Maven and SonarCloud packages
      uses: actions/cache@v3
      with:
         path: |
            ~/.m2
            ~/.sonar/cache
         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
         restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      working-directory: com.drago.manuel.scommesse
      env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: xvfb-run mvn verify -Pjacoco ${{ matrix.maven-args }}